---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: false
  ansible_verbosity: 1
  ansible_version: latest
  require_ruby_for_busser: false
  require_chef_for_busser: true
  hosts: all
  roles_path: ../

platforms:
  - name: centos/7
  - name: ubuntu-16.04

suites:
  - name: default
