---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  roles_path: roles
  ansible_verbose: true
  ansible_verbosity: 2
  ansible_version: latest
  require_ruby_for_busser: false
  require_chef_for_busser: true
  hosts: all
  roles_path: ../

platforms:
  - name: centos/7
  - name: ubuntu-14.04

suites:
  - name: default
