---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.0.0.0

sudo: required
services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt ruby

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - sudo gem install busser --no-ri --no-rdoc
  - sudo busser plugin install busser-bats

script:
  - ansible-galaxy install -r requirements.yml
  - echo localhost > inventory
  # Run syntax check
  - ansible-playbook -i inventory --syntax-check test/integration/default/default.yml
  # Run playbook locally => Not Working because of unknown error saying `refusing to convert between file and link for /usr/local/bin/docker-compose`
  # - ansible-playbook -i inventory --connection=local --become -vvvv test/integration/default/default.yml
  # Run the Test Kitchen tests.
  # - sudo /opt/busser/vendor/bats/bin/bats ./test/integration/default/bats/*.bats

notifications:
  slack: $SLACK_NOTIFICATION
